require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara

AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb
    - gemfiles/*
    - vendor/bundle/**/*
    - bin/bundle

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

RSpec/ExampleLength:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - db/*
    - config/**/*

Metrics/AbcSize:
  Exclude:
    - app/controllers/**/*

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Lint/MissingSuper:
  Exclude:
    - app/components/**/*
